kind: pipeline
name: default

steps:
  - name: build
    image: node:latest
    commands: 
      - npm install
      - npm test

  - name: publish
    image: plugins/docker
    settings:
      registry: Dockerfile
      repo: quilarque1/getcotizacion
      username:
        from_secret: quilarque1
      password:
        from_secret: d9RlzVH15m